apiVersion: apps/v1
kind: Deployment
metadata:
  name: vgl-server-deployment
spec:
  selector:
    matchLabels:
      app: vgl-server
  replicas: 3
  template:
    metadata:
      labels:
        app: vgl-server
    spec:
      containers:
        - name: vgl-server-k8s
          image: vgl-server-k8s:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : db-credentials
                  key :  POSTGRES_USER

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : db-credentials
                  key :  POSTGRES_PASSWORD

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: vgl-server-svc
spec:
  selector:
    app: vgl-server-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.