# Define a 'Persistent Volume Claim (PVC) for postgres Storage, dynamically provisioned by cluster.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim # Name of PVC essential for identifying the storage data.
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   # This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    # This will tell kubernetes about the amount of space we are trying to claim.
---
# Configure 'Deployment' of postgres server.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  selector: # Postgres Pod Should contain same labels.
    matchLabels:
      app: postgres
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors.
        app: postgres
        tier: database
    spec:
      containers:
        - image: postgres:16.0 # Image from docker-hub.
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts: # Mounting volume obtained from Persistent Volume Claim.
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgres #This is the path in the container on which the mounting will take place.
      volumes:
        - name: postgres-persistent-storage # Obtaining 'volume' from PVC.
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
# Define a 'Service' To Expose postgres to Other Services.
apiVersion: v1
kind: Service
metadata:
  name: postgres  # DNS name.
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector: # Postgres Pod Should contain same labels.
    app: postgres
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant.
